spring:
  datasource:
    continue-on-error: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fmall?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root123456

    #druid 下面为连接池的补充设置，应用到上面所有数据源中
#    type: com.alibaba.druid.pool.DruidDataSource
    #初始化大小，最大，最小
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis : 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis : 300000
    validationQuery : SELECT 'x'
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements : true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties:
      druid:
          stat:
            mergeSql: true
            slowSqlMillis: 5000



  redis:
    host: 127.0.0.1
    password: Redis123456
    port: 6379
    timeout: 100000
    jedis:
        pool:
          max-active: 1000
          min-idle: 1
          max-idle: 100
          max-wait: -1ms

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

appid: wx431724e5bd79b294
mchId: 1604890711
api : yHJ9VfWbI0CYXImG27Q63X43I5If9uak
apiV3Key : FYv9TBwOUFskKtHs9JBBmviPk3WkfaOf
mchSerialNo : 76B0E56D4C62068F0D2D1007CA150BA3B4267148
